### ISSUE TITLE
Include a master pykmer script

### ISSUE THREAD

**Issue by tseemann** [drtconway/pykmer#3]
Once you are able to extend this beyond a library only it would be good if you could install a single tool called `pykmer` in the `PATH` .

This tool would have sub-commans (ala `samtools` etc) to do common kmer tasks.

Although it might not be used as a generic tool by everyone, it would be useful in teaching, and as the basis for people's bespoke tools.

I believe the `argparse` and `click` modules support subcommands.

**Comment by drtconway** [comment]
I totally agree. Ben and I decided for various reasons that it should be a separate project - zotmer (following your advice on naming). I have a repo beside this one with zotmer. It's coming along nicely, but not quite yet ready to put up on pip.

FWIW, in the end we went with docopt.
